CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  telephone VARCHAR(11) NOT NULL
);

CREATE TABLE foods (
  id SERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  img VARCHAR(200) NOT NULL,
  count INTEGER NOT NULL
);

CREATE TABLE orders (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  food_id INTEGER REFERENCES foods(id),
  food_name VARCHAR(50) NOT NULL,
  quantity INTEGER NOT NULL
);


